### ISSUE TITLE
Missing parameter: installPluginBundleFromFile -> installAllPluginsForAllUsers

### ISSUE THREAD

**Issue by jpjob314** [opensourceBIM/Collada#3]
Hi Ruben,

I'm interested in updating this project to allow export in collada format per query / nodes.
I fixed the pom.xml line 161 to last bimserver pluginbase :
		<dependency>
			<groupId>org.opensourcebim</groupId>
			<artifactId>pluginbase</artifactId>
			<version>1.5.67</version>
		</dependency>
and generated a jar with eclipse neon 2 but I'm getting the following error : "Missing parameter: installPluginBundleFromFile -> installAllPluginsForAllUsers" while importing plugin to the server in the "Available Plugin Bundles" section. Any advice ?

Thanks

**Comment by jpjob314** [comment]
It looks like this error comes from /apps/bimviews/?page=ServerSettings&subpage=InstalledPluginBundles page instead of the jar itself ...

**Comment by rubendel** [comment]
BIMvie.ws had not been updated to reflect the added arguments to this call, just did that. Will be in the new release of BIMvie.ws

**Comment by jpjob314** [comment]
Thanks ! I'll keep you in touch
